base_model: linear
ckpt: dummy/uber_tlc_hourly.ckpt
context_length: 336
dataset: crypto
device: cuda:0
diffusion_config: diffusion_small_config
init_skip: false
iterations: 20
num_samples: 100
prediction_length: 24
refiner_configs:
- guidance: MSE
  lr: 0.1
  refiner_name: most_likely
use_features: false
use_lags: true
